### ISSUE TITLE
Epic: Support optional SDK workload composition

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11164]
[Workloads overview spec](https://github.com/dotnet/designs/pull/100)

This Epic tracks the work needed for workload "composition", ie hooking up the right assets from a workload once they are installed.

This spec covers a lot of the details for how this will be implemented: [Workload resolution in MSBuild](https://github.com/dotnet/designs/pull/104)

- [x] [Add features to MSBuild SDK Resolver interface to support optional SDK workloads](https://github.com/microsoft/msbuild/issues/5239)
- [x] [Write library for reading workload manifests](https://github.com/dotnet/sdk/issues/11230)
- [x] [Create MSBuild SDK resolver for workloads](https://github.com/dotnet/sdk/issues/11228)
- [x] [Support workloads in Microsoft.NET.Sdk](https://github.com/dotnet/sdk/issues/11229)
- [x] [Workload library pack](https://github.com/dotnet/sdk/issues/11493)
- [x] Template Engine - [Workload work with template](https://github.com/dotnet/sdk/issues/11326)

#### .NET 6
- [ ] Project system - [Trigger in-product acquisition based on MissingWorkloadPack items](https://github.com/dotnet/project-system/issues/6080)
- [ ] Create validator for workloads to make sure that they follow the right format and guidance
- [ ] [Workload commandline resolver](https://github.com/dotnet/sdk/issues/11495)

**Comment by wli3** [comment]
We also need to have a new CLI command resolver to find the tools from a workload
