### ISSUE TITLE
Epic: Support targeting iOS and Android with the .NET SDK

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11165]
This epic tracks the work to support targeting iOS and Android in the .NET SDK.

This includes work in the .NET SDK, MSBuild, and NuGet to support new TargetFrameworks, or other related work.  It does not cover what will be delivered in the the iOS and Android workloads, nor the workload system itself (which is covered in #11164).

- [x] NuGet - [Support parsing operating system information from TargetFramework](https://github.com/NuGet/Home/issues/9240)
- [x] MSBuild - [Add intrinsic functions to parse TargetFramework components (implemented by calling NuGet APIs)](https://github.com/microsoft/msbuild/issues/5171)
- [x] Parse TargetFramework into component properties in TargetFrameworkInference.targets (via new MSBuild intrinsic functions): #11231
- Normalize TargetPlatformIdentifier casing
  - [x] Windows
  - [ ] Android (.NET 6)
  - [ ] iOS and other Apple platforms (macOS, tvOS, watchOS) (.NET 6)
- [x] Fail build if an unsupported or unknown operating system is specified in TargetFramework: #11232
- [ ] Set default TargetPlatformVersion based on TFI, TFV, and TPI
  - [x] For Windows: #11233
  - [ ] For iOS and Android (in the corresponding workloads) .NET 6
- [x] Support providing OS APIs from targeted platform: #11234
- [x] Add preprocessor symbols for OS: #11236
  - This also covers accumulating preprocessor symbols so that newer versions also include versioned symbols for the past
- [x] Generate target platform assembly attributes: #11239
- [x] Default OSMinimumVersion to TargetPlatformVersion, and error if it is higher than TargetPlatformVersion
- Support platform-specific OS minimum version attributes, translating them to OSMinimumVersion if current target matches
  - [ ] WindowsMinimumVersion -- .NET 6
  - [ ] IOSMinimumVersion -- .NET 6
  - [ ] AndroidMinimumVersion -- .NET 6
- [x] Don't include OS info in runtimeconfig tfm: #11010
- [x] Multitargeting support for WindowsDesktop
  - [x] Support targeting WPF and WindowsForms using Microsoft.NET.Sdk (instead of Microsoft.NET.Sdk.WindowsDesktop): https://github.com/dotnet/wpf/pull/3111
  - [x] https://github.com/dotnet/sdk/pull/12106
  - [x] Add warnings for WindowsDesktop targeting: #11241
- [x] Infer WinExe output type as appropriate #11398

#### .NET 6
Open design issues: #11275
- [ ] iOS / Android workloads: Support sdk-style projects for iOS / Android
  - Default item globs
  - Other defaults, and integration into Microsoft.NET.Sdk
- [ ] dotnet tools X net5.0 #12055
