### ISSUE TITLE
Epic: Miscellaneous .NET 5 work

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11225]
This epic tracks work targeting .NET 5 which is not covered by any of the other epics.

- [x] Provide WinRT APIs for projects targeting Windows #11556 
- [x] When global.json specifies an SDK that can't be found, don't block project load in Visual Studio: #11238
- [x] Build warning when targeting out of support SDK #12060
- [x] Add output to dotnet run #12227 (Web SDK)
---
- [ ] Get latest runtime patch information without requiring users to update the SDK: #11226 
- [ ] Include PDBs and XML files from packages in project output: #1458
- [ ] Support setting a common root output path via a single property: #867

#### .NET 6
- [Avoid downloading MSBuild SDKs from NuGet on the VS UI thread](https://github.com/dotnet/project-system/issues/6069)
- Self-contained apps can use the Mono VM (and AOT) on desktop operating systems: #11227
- [ ] Remaining cswinrt work #12387
