### ISSUE TITLE
Move NETStandard2.0 net461 support into targets

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1267]
Today the `netstandard2.0` support for `net461` is delivered via the `NETStandard.Library.NETFramework` package.  Initially we had planned on having the tooling automatically inject a reference to this whenever needed.  That has turned out to be problematic for various reasons.  As a result we're planning instead to just move all of this support to targets.

Let this issue summarize the work that is required to do so.
- [x] Port / author tasks and targets to support `netstandard2.0` in `net461: #1286
  - [x] Don't include `netstandard2.0` libraries when `nestandard.dll` is not in the closure. (necessary performance fast-path to not bloat hello-world).
- [x] Include tasks and targets for .NET 4.6.1 support for .NET Standard 2.0 in SDK insertion to CLI repo: #1288
- [x] Add test coverage for  `netstandard2.0` support for `net461`: #1287
  - [x] Ensure retargeting experience works correctly in SDK and legacy projects. (test)
  - [x] Ensure future framework that includes `netstandard2.0` support does not use these. (test)
  - [x] Ensure binaries in support set are serviceable through packages. (test)
- [x] Include `netstandard2.0` support for `net461` in the .NET CLI: dotnet/cli#6737
- [x] Include `netstandard2.0` support for `net461` legacy projects in VS 2017 via some VSIX: dotnet/cli#6738
- [x] Include `netstandard2.0` support for `net461` legacy projects in VS 2015.  Via some machine-wide MSI/VSIX: dotnet/cli#6739
- [ ] NuGet flags missing support of one of the above installers when installing a ns2.0 assembly into a desktop project: NuGet/Home#5325

/cc @dsplaisted @terrajobst

**Comment by weshaggard** [comment]
>Don't include netstandard2.0 libraries when nestandard.dll is not in the closure. (necessary performance fast-path to not bloat hello-world).

If we do that then that means net461 will not have support for netstandard < 2.0. Is that what we want? How would someone consume a netstandard1.6 (i.e System.Runtime based) netstandard library?

**Comment by dsplaisted** [comment]
@weshaggard A NuGet package that targets .NET Standard 1.x would have a package dependency on the NETStandard.Library 1.6.1 package, which as I understand brings in the needed support.  IE, this is already a supported scenario and we aren't changing how it works.

**Comment by weshaggard** [comment]
It may or may not have a package dependency to NETStandard.Library 1.6.1 and there are also other nuget packages that target netstandard1.6 that are higher level that would need to be referenced in some cases. This scenario has always been really bad and the support package was going to help those scenarios as well as the netstandard2.0 scenarios but with this change that will no longer be the case. Perhaps we can make that call but I want us to be intentional about it.

**Comment by weshaggard** [comment]
Another item that we need to make sure we have strategy for is how we update the binaries that are part of this support package. If we have to service one of them what do developers need to do to get an updated set of assemblies included into their application.

**Comment by dsplaisted** [comment]
For servicing, the idea is

- These assemblies ship with MSBuild, so we can ship an updated MSBuild with updated assemblies
- To take a newer version of an assembly before then, you could reference a NuGet package, and conflict resolution should pick the more recent one

**Comment by weshaggard** [comment]
>To take a newer version of an assembly before then, you could reference a NuGet package, and conflict resolution should pick the more recent one

That implies that there will still be a nuget package published is that still the plan or are we only going to publish a package if it needed for a critical servicing?

**Comment by dsplaisted** [comment]
> That implies that there will still be a nuget package published is that still the plan or are we only going to publish a package if it needed for a critical servicing?

I think the assemblies that have code in them (e.g. ValueTuple) generally already ship in a NuGet package.  We don't plan to publish any new packages (ie with the facades) unless we need to.

**Comment by weshaggard** [comment]
While that might be true for ValueTuple that isn't currently true for the others like System.Net.Http so we would have to start shipping that individual package again if we needed to service it. That strategy can of course work I'm just trying to make sure we understand the plan.

**Comment by akoeplinger** [comment]
What's the plan for VS for Mac / Mono with this?

**Comment by ericstj** [comment]
@akoeplinger the updates go into the CLI's copy of MSBuild and VS's copy of MSBuild.  If VS for Mac is using the CLI-MSBuild it will just work when picking up a new version.  If instead it is laying out its own copy of MSBuild then that will need to be updated as well.  Do you happen to know which is the case?

**Comment by akoeplinger** [comment]
@ericstj VS for Mac is building with the MSBuild that is shipped with Mono. If there will be a new MSBuild then we can pick that up, I was mostly confused because the issue mentions needing some VSIX/MSIs for the support.

**Comment by ericstj** [comment]
It's not really a new MSBuild, just some targets and a task dll.  See: https://github.com/dotnet/sdk/pull/1279.  We need a VSIX to install these into VS 2017's MSBuild, an MSI to install them into VS 2015's MSBuild, and they can be bundled inside the CLI layout.

**Comment by akoeplinger** [comment]
Ok. As far as I know we're already bundling the Sdks in the MSBuild we ship so I guess we just need to bundle this as well.

**Comment by dsplaisted** [comment]
@akoeplinger I've filed #1294 to track getting this into the Mono MSBuild

**Comment by nguerrera** [comment]
Closing since the only remaining checkbox is tracked by https://github.com/NuGet/Home/issues/5325
