### ISSUE TITLE
.NET 6 Support targeting iOS and Android with the .NET SDK

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#12899]
This epic tracks the work to support targeting iOS and Android in the .NET SDK.  This was generated from the work that was cut from #11165 as not in scope for .net 5

This includes work in the .NET SDK, MSBuild, and NuGet to support new TargetFrameworks, or other related work.  

Open design issues: #11275
- [ ] dotnet tools X net5.0 #12055 (optional for .NET 6)

**External to Workloads**
- Normalize TargetPlatformIdentifier casing
  - [x] Windows
  - [ ] Android (.NET 6)
  - [ ] iOS and other Apple platforms (macOS, tvOS, watchOS) (.NET 6)
- Support platform-specific OS minimum version attributes, translating them to OSMinimumVersion if current target matches
  - [ ] WindowsMinimumVersion -- .NET 6
  - [ ] IOSMinimumVersion -- .NET 6
  - [ ] AndroidMinimumVersion -- .NET 6
- [ ] Set default TargetPlatformVersion based on TFI, TFV, and TPI
  - [x] For Windows: #11233
  - [ ] For iOS and Android (in the corresponding workloads) .NET 6
- [ ] iOS / Android workloads: Support sdk-style projects for iOS / Android
  - Default item globs
  - Other defaults, and integration into Microsoft.NET.Sdk

**Comment by marcpopMSFT** [comment]
No more planned work in this space for 6.0.1xx so closing out.  We'll leave the specific tools item open.
