### ISSUE TITLE
Miscellaneous .NET 6 work

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#12900]
This epic covers work not included in other .net 6 epics.  This is a carryover of the work not completed in #11225
- [ ] Get latest runtime patch information without requiring users to update the SDK: #11226 
- [ ] Include PDBs and XML files from packages in project output: #1458
- [ ] Support setting a common root output path via a single property: #867
- [Avoid downloading MSBuild SDKs from NuGet on the VS UI thread](https://github.com/dotnet/project-system/issues/6069)
- Self-contained apps can use the Mono VM (and AOT) on desktop operating systems: #11227
- [ ] Remaining cswinrt work #12387
