### ISSUE TITLE
Finish optional SDK workload composition

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#12901]
[Workloads overview spec](https://github.com/dotnet/designs/pull/100)

This Epic tracks the work needed for workload "composition", ie hooking up the right assets from a workload once they are installed.

This spec covers a lot of the details for how this will be implemented: [Workload resolution in MSBuild](https://github.com/dotnet/designs/pull/104)

#### .NET 6
- [x] Project system - [Trigger in-product acquisition based on MissingWorkloadPack items](https://github.com/dotnet/project-system/issues/6080) (also tracked by Epic dotnet/sdk#14957)
- [ ] #22224
- [ ] [Workload commandline resolver](https://github.com/dotnet/sdk/issues/11495) (optional for .NET 6)
- [x] [Add caching for workload resolution, and enable by default](https://github.com/dotnet/sdk/issues/13849)
- [x] #18489
- [ ] Honor the workload installation record when doing workload resolution
