### ISSUE TITLE
5.0.1xx RC1 Blocking Issues Tracking

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#13080]
- [x] MSBuild insertion #13078: @dsplaisted and @rainersigwald investigating test failures
- [x] Merge preview 8 internal #13079: @wli3
- [x] NuGet insertion: @nkolev92 to promote build
- [x] Fix MSBuild static graph failures #13081: @dsplaisted 
- [x] TargetFramework changes #13093:: @dsplaisted 
  - Fix warning icons on packages
    - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1165638
    - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1161673
  - Fix scaffolding failures: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163171
- [ ] Audit TargetFramework / TargetFrameworkMoniker / etc. usage in SDK.  Most of these changes are probably covered by the WIP changes previously mentioned
- [x] F# projects won't build https://github.com/dotnet/sdk/issues/12954: @sfoslund 
- [x] Reenable project to project reference with TF net5.0-windows tests on full framework (https://github.com/dotnet/sdk/pull/13096/commits/a3d02c6f61c1e2a65648bc76b5fec2410b5ba741): @sfoslund
- [ ] Cannot build WinUI sample in preview 8 https://github.com/dotnet/sdk/issues/13135 @wli3
- [x] C++/CLI #12916

**Comment by nkolev92** [comment]
@kartheekp-ms can you please ping this issue when you have started a NuGet insertion.

**Comment by kartheekp-ms** [comment]
@nkolev92 - I have executed following command for `NuGet` insertion into `dotnet`.
```
C:\repos\arcade> darc add-build-to-channel --id 61474  --channel "VS 16.8" --source-branch master
Build 61474 will be assigned to target channel(s) once this build finishes publishing assets: https://devdiv.visualstudio.com/devdiv/_build/results?buildId=4007396
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Build '61474' was successfully added to the target channel(s).
Assigning build '61474' to the following channel(s):

        VS 16.8

Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        3501ddedc274ac10d4b135856b7593a6bb8a72f1
Build Number:  5.8.0.6783
Date Produced: 8/21/2020 6:07 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4001395
BAR Build Id:  61474
Released:      False
Channels:
The following repos/branches will apply this build immediately:
  https://github.com/dotnet/sdk @ master
  https://github.com/dotnet/sdk @ release/5.0.1xx
```

**Comment by dsplaisted** [comment]
Looks like this is the NuGet insertion PR for 5.0.1xx: #13090

**Comment by nkolev92** [comment]
Looks like the PRs were created. 

5.0.1xx PR is https://github.com/dotnet/sdk/pull/13090.

**Comment by kartheekp-ms** [comment]
NuGet insertion PR for master branch: #13091
