### ISSUE TITLE
Optional Workload Acquisition

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#14957]
This epic covers the work to be able to acquire an optional workload
- [ ] Given the npkg and manifest from the workload owner, convert to an MSI
- [ ] Acquisition of optional workloads in VSfM
- [ ] When a workload is missing, trigger the acquisition experience
- Acquisition of the workloads
  - [ ] Non-admin install of the workload
  - [ ] Uninstall and update for the workloads
  - [ ] Admin install

**Comment by marcpopMSFT** [comment]
FYI to @wli3 as we closed out the optional workload issues for .net 6.  Thanks for the hard work!
