### ISSUE TITLE
SDK managed workload installer

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#16483]
Top level: Implement the [.NET SDK managed workload installer](https://github.com/dotnet/designs/blob/4cd0cf814d875301cc291b4ae8f1068363b68c15/accepted/2021/workloads/workload-installation.md#net-sdk-managed-installation), which will be used to local/non-admin scenarios.

- [x] Basic nuget package download API: https://github.com/dotnet/sdk/pull/16443. This will be expanded later, see https://github.com/dotnet/sdk/issues/16470
- [x] Implement workload install process (layer above IAL): [spec](https://github.com/dotnet/designs/blob/4cd0cf814d875301cc291b4ae8f1068363b68c15/accepted/2021/workloads/workload-installation.md#workload-installation-process). This is necessary since this will be the first workload installer implemented. https://github.com/dotnet/sdk/pull/16530
- [x] Implement installer abstraction layer: [spec](https://github.com/dotnet/designs/blob/4cd0cf814d875301cc291b4ae8f1068363b68c15/accepted/2021/workloads/workload-installation.md#installer-abstraction-api) https://github.com/dotnet/sdk/pull/16530
- [x] Write first implementation of the installer abstraction layer, the SDK managed installer: [spec](https://github.com/dotnet/designs/blob/4cd0cf814d875301cc291b4ae8f1068363b68c15/accepted/2021/workloads/workload-installation.md#net-sdk-managed-ial-implementation). 
  - [x] Write basic install: https://github.com/dotnet/sdk/pull/16530
  - [x] Write garbage collection: https://github.com/dotnet/sdk/pull/16530
  - [x] Per https://github.com/dotnet/sdk/pull/16530#discussion_r608237834, refactor workload installation into a separate project https://github.com/dotnet/sdk/pull/16823
  - [x] Write offline cache logic: https://github.com/dotnet/sdk/pull/17324
  - [x] Add `--print-download-link-only` implementation (required for VS4Mac): https://github.com/dotnet/sdk/pull/17324
  - [x] Write manifest updates logic: https://github.com/dotnet/sdk/pull/16891
- [x] Preserve executable permission on unix https://github.com/dotnet/sdk/issues/16566
- [x] A command to detect if a workload is installed already (required by VSMac installer) #17324 
- [x] A command To install previously cached download packages #17324 
- [x] Add manifest caching to offline cache install (more detail: https://github.com/dotnet/sdk/pull/17324#discussion_r627964123)
- [x] Implement extra install options (including --configfile, --add-source, etc): https://github.com/dotnet/sdk/pull/17893

**Comment by wli3** [comment]
One the spec is decided. We need to create list on code level to have more detail

**Comment by wli3** [comment]
"A command to detect if a workload is installed already (required by VSMac installer)". VS for mac installer need to check if a component exists. Something like _dotnet workload exist android_. And note, the return need to be machine readable.
![image](https://user-images.githubusercontent.com/6993335/102674092-913c5380-4149-11eb-8682-399d7115b3ea.png)

> A command to download packages without installing them
>  an option should be available to download highest SDK's manifest's workloads, even though this version of SDK may not support it
>  A command To install previously cached download packages

This is a scenario required by VSMac updater. While the user is using VSMac, the updater could download packages in the background. And then later prompts the user to install them in bulk. .NET SDK need to fit in this case. When there is a new SDK available("suggest to update" every 4 month, "have to update" every year), the current SDK may not be able to work with the latest workload, but it should be able to download them. So that, during the install process, the new SDK (download by VSMac), will be installed first. The downloaded workload will be installed later. The install process do not need to hit the internet. There is a chance the older SDK cannot even process the higher version SDK's manifest. At this point we would do a best effort. We expect the manifest would be stable after the first year.

**Comment by sfoslund** [comment]
@wli3 you mentioned in standup that we'll need to remove the mock logic from WorkloadInstallCommand now that we have the managed installer checked in. It looks like most of the mock logic deals with the `FromCache` and `PrintDownloadLinkOnly` options, which aren't implemented elsewhere. Do we still want to remove all of it? If so, I can go ahead and include that in my next PR.

**Comment by wli3** [comment]
@sfoslund that is a good point. I think the "real" command and the mock commands are separated by FromCache and PrintDownloadLinkOnly flag completely. So, keeping these mock logic should be fine. When FromCache and PrintDownloadLinkOnly is used. It goes to the mock logic. Everything else goes to the real implemetation.

**Comment by sfoslund** [comment]
@wli3 Okay great. I'm planning on implementing the offline cache logic soon (starting this week hopefully). I can do the print download flag part too, is that in Daniel's spec or is there somewhere else I should look for details?

**Comment by wli3** [comment]
@sfoslund I don't think Daniel's spec covers that. But I don't think we really need a spec to do the implementation.

**Comment by sfoslund** [comment]
What is the desired behavior for the print download flag then? Just print the json formatted list of urls for downloading the pack nuget packages? Should it print and then continue with the install or only print when this flag is present? Should it deal with the manifests at all (ie print the manifest urls too)?

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/16506#issue-600259767
Overview of the contract

> Just print the json formatted list of urls for downloading the pack nuget packages? 

You need my nuget change be in first to get the URL. I guess at this point I will not wait for Daniel. It does not need "formatted". Just machine readable json is enough (with the ======= thing to help parse). It will be a json list of URLs. All and only all nupkgs required for the requested workloads. (dotnet workload install mobile-ios will only return a list of nupkgs required by mobile-ios). 

> Should it print and then continue with the install or only print when this flag is present? 

It will just print and then exit. We expect VSMac later to call `dotnet workload install mobile-ios --from-cache /cache/dir` to resume the install.

> Should it deal with the manifests at all (ie print the manifest urls too)?

Yes. Instead of SDK telling nuget to download nupkgs, we ask VSMac to do so. But which nupkgs(which packs compose a workload) to download still need manifest information.

**Comment by sfoslund** [comment]
Closing this as all tasks are merged.
