### ISSUE TITLE
API Compat/Package Validation roadmap

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#18678]
This meta issue captures the roadmap for API Compat and Package Validation.

Order of tasks is the order in which we should tackle them (they can be done simultaneously).

Sizes:
S: 1 day.
M: 2 - 3 days.
L: 1 week.
XL: 1+ weeks.

## P0:
- [x] https://github.com/dotnet/sdk/issues/17365 (Size: S)
- [x] https://github.com/dotnet/sdk/issues/17928 (Size: M)
- [x] https://github.com/dotnet/sdk/issues/18679 (Size: S)
- [x] https://github.com/dotnet/sdk/issues/18680 (Size: M) (PR https://github.com/dotnet/sdk/pull/18929)
- [x] https://github.com/dotnet/sdk/issues/18685 (Size: S)
- [x] https://github.com/dotnet/sdk/issues/18702 (Size: S)
- [x] https://github.com/dotnet/sdk/pull/19123 (Size: S)
- [x] https://github.com/dotnet/sdk/issues/17366 (Size: S)
- [x] https://github.com/dotnet/sdk/pull/19209 (Size: M)
- [ ] https://github.com/dotnet/sdk/issues/18676 (Size: L)

## P1:
- [ ] https://github.com/dotnet/sdk/issues/18677 (Needed for dotnet/runtime, wcf, etc, Size: M)
- [ ] https://github.com/dotnet/sdk/issues/18681 (Size: L)
- [ ] https://github.com/dotnet/sdk/issues/18682 (Size: M)
- [ ] https://github.com/dotnet/sdk/issues/18683 (Size: S)
- [ ] https://github.com/dotnet/sdk/issues/18165 (Size: ?)
- [ ] https://github.com/dotnet/sdk/issues/19614 (Size: S)

## P2:

- [ ] https://github.com/dotnet/sdk/issues/18582 (Size: M)
- [ ] https://github.com/dotnet/sdk/issues/17364 (Size: M)

**Comment by safern** [comment]
Super seeded by: https://github.com/dotnet/sdk/issues/23910
