### ISSUE TITLE
Miscellaneous .NET 7 work

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#22362]
This epic covers work not included in other .net 7 epics. This is carryover of work from #12900

- [ ] Get latest runtime patch information without requiring users to update the SDK: #11226 
- [x] Include PDBs and XML files from packages in project output: #1458
- [ ] Support setting a common root output path via a single property: #867
- [ ] Avoid downloading MSBuild SDKs from NuGet on the VS UI thread](https://github.com/dotnet/project-system/issues/6069)
- [ ] Figure out relationship between Directory.Build.targets and workloads #15505 
---
- [ ] Solve the problem of needing to have a default target import prior to the workload targets (as directory.build.targets is after): https://github.com/dotnet/designs/pull/224
- [ ] Remaining cswinrt work #12387

**Comment by marcpopMSFT** [comment]
Did all we were going to do for .net 7 so closing out.
