### ISSUE TITLE
Update Workload creation to version by preview to take advantage of #22446

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#23373]
See #22446 for details on the original work
- [x] Arcade work to enable workload msis to install to a preview version dotnet/arcade#8365
- [x] Get workload owners to pick up new Arcade versions when they create 7.0.100 band workloads
- [x] Finalizer work to support separate preview bands dotnet/installer#13087
- [x] CLI install engine logic review to ensure this works #23502
- [x] Review msi package naming
- [x] Test with rollback and fallback (but not rollback + fallback)

**Comment by dsplaisted** [comment]
Linking #22446

**Comment by joeloff** [comment]
Finalizer changes: https://github.com/dotnet/installer/pull/13087
SDK changes: https://github.com/dotnet/sdk/pull/23502
Arcade changes: https://github.com/dotnet/arcade/pull/8365
