### ISSUE TITLE
Enable workloads on arm64

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#27243]
Today, workloads install the x64 package on arm64 machines which doesn't work very well. We should have native arm64 support for workloads scenarios.
- [x] Produce arm64 msi that installs to arm64 location
- [x] Produce copies of swix authoring for both MachineArch=arm64 and not because 17.0/17.2 don't support this.
   - [x] Need to double check with VS Setup that this is required <-- they indicated it probably was
- [x] Update swix tooling to support arm64
- [x] Workload owners update manifests to bring in win-arm64 versions for packs
  - [ ] https://github.com/dotnet/emsdk/pull/234
  - [x] https://github.com/dotnet/emsdk/pull/231
  - [ ] https://github.com/dotnet/emsdk/pull/232
  - [ ] https://github.com/dotnet/runtime/pull/68994
- [x] Some workloads may want aliasing to install the x64 components into the arm64 folder as emulated
- [ ] Need to change the templates for swix authoring in arcade
- [ ] Retest finalizer logic
- [ ] Verify workload list and search
- [ ] Build impact to runtime

**Comment by baronfel** [comment]
We did this! It's released starting in vs17.6 preview 1, and you can read more about it [here](https://devblogs.microsoft.com/visualstudio/try-visual-studio-2022-v17-6-preview-1/#ARM64)
