### ISSUE TITLE
Enable dotnet SDK to support targeting iOS with NativeAOT

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/sdk#30068]
## Description

Supporting NativeAOT on iOS platforms as an experimental feature in .NET8 requires changes in dotnet SDK, as outlined in https://github.com/dotnet/runtime/issues/80905. It does support targeting iOS platforms but that defaults to referencing MonoAOT runtime and compiler packages.

## Tasks

 - [ ] Adjusted NativeAOT build integration targets to include target OS in the response file generation
 - [ ] Used custom MSBuild targets to overwrite MonoAOT runtime package with locally built NativeAOT framework and libraries
 - [ ] Disabled invoking MonoAOT compiler
 - [ ] Used custom MSBuild targets to invoke ILCompiler and adjust linking proper object files and libraries when linking the native code
