### ISSUE TITLE
Add performance test for WPF and Winform

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#3223]
- [x] Add hello world test for WPF and Winform for netcore and full framework, make sure infrastructure supports that.
- [x] Add large realistic project
- [ ] Move out of benchview
- [ ] Change the PowerBI view to better compare full framework to non-full framework
==================================
- [x] Combine RunPerfTestsOnHelix.fullframework.cmd into one
- [x] Solve bench view upload collision

**Comment by wli3** [comment]
And I am looking for good test assets for WPF and WinForm to test SDK build performance against.
 
I think it should
 
1.	Be large with many p2p and nuget reference to represent real world scenario(although is nuget used a lot in WPF and WinForm era?).
2.	Has both ported core version and full framework version(to be used as a base line).

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/3349
