### ISSUE TITLE
[Containers] Improve container integrations with editors and tools to expand usage

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#35552]
Now that the Container tools are well-grounded, we should integrate them deeper with our editors and partner tools:

## Deployment
* [ ] [Integrate with `azd`](https://github.com/dotnet/sdk-container-builds/issues/313)

## Editors
* [ ] https://github.com/dotnet/sdk-container-builds/issues/503
* [ ] https://github.com/dotnet/sdk-container-builds/issues/502

## CLI
* [ ] https://github.com/dotnet/sdk/issues/26161
* [ ] https://github.com/dotnet/sdk/pull/29817

## Capabilities
* [ ] https://github.com/dotnet/sdk-container-builds/issues/87
