### ISSUE TITLE
Extensions Wishlist

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/sdk#7122]
This issue tracks asks for additional CLI Tools that folks would like to have access to. Think of these as `Up For Grabs` work items for folks that want to build CLI extensions. Let us know if you're interested in taking one of these on!

 - [ ] ILAsm dotnet/sdk#5307
 - [ ] ILDasm dotnet/sdk#5307
 - [ ] C# REPL dotnet/sdk#5628
 - [ ] F# REPL dotnet/sdk#5628
 - [x] List all installed versions of the .NET SDK. 
`dotnet allversions`
Contributed 11/10/2016 by @pgroene. [source](https://github.com/pgroene/dotnet-allversions).
