### ISSUE TITLE
Support targeting .NET Core 2.0 and .NET Standard 2.0 without specifying a preview versions in the project

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#972]
Currently the templates in the 2.0 CLI [hard code the `RuntimeFrameworkVersion` property](https://github.com/dotnet/templating/blob/bfe0d9d6ba85cdaa17a81ef4cafe635a41ae2ac6/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj#L6) when targeting .NET Core 2.0, and [hard code the `NetStandardImplicitPackageVersion`](https://github.com/dotnet/templating/blob/bfe0d9d6ba85cdaa17a81ef4cafe635a41ae2ac6/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj#L5) when targeting .NET Standard 2.0 in order to use a preview version of the corresponding platform package that supports 2.0.

This doesn't easily support retargeting from 1.x projects, or upgrading to a new preview (plus it makes the project files uglier).

We should make it so that the preview version of the tools knows which preview version of the Microsoft.NETCore.App and NETStandard.Library packages to use when the `TargetFramework` is netcoreapp2.0 or netstandard2.0.

### Sub-tasks

- [x] Consume bundled version props from SDK (https://github.com/dotnet/sdk/pull/1012)
- [x] Deploy generated bundled version props with CLI (https://github.com/dotnet/cli/pull/6102) 
- [x] Package bundled version props in VS insertion nupkg (https://github.com/dotnet/cli/pull/6136)
- [x] Add setup authoring to deploy bundled version props for VS
  - Speculative change made in dev/nicholg/cli-msbuild-extensions branch in VSO: [commit link](https://devdiv.visualstudio.com/DevDiv/_git/VS/commit/9aad46cbb4a48fa6cc6fb96c01306926e8f26a5c)
  - @livarcocc is going to pick it up from there
- [x] Remove NetStandardImplicitPackageVersion and RuntimeFrameworkVersion from templates. 
  - Mostly https://github.com/dotnet/templating/issues/466, but there is some correpsonding code in dotnet/cli to be deleted afterwards. 
  - My understanding is that @mlorbetske will handle this when he inserts the new templates in to the CLI

**Comment by nguerrera** [comment]
Sub tasks:

- [ ] Consume bundled version props from SDK
- [ ] Deploy generated bundled version props with CLI
- [ ] Package bundled version props in VS insertion nupkg
- [ ] Remove NetStandardImplicitPackageVersion and RuntimeFrameworkVersion from templates
- [ ] Add setup authoring to deploy bundled version props for VS
