### ISSUE TITLE
Flexibility in SDK install folder

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/sdk#9802]
As a Visual Studio user, I can specify the folder for the .NET Core SDK that is different from c:\program files\dotnet so that I can reduce the footprint on the system drive.
_________________________________
Visual Studio will have flexibility in its installation location - therefore, SDK will also have flexibility in its installation location.

**Scenarios**
Installations:
1. an SDK installation chained from a Visual Studio installation instance
2. a 'stand-alone' SDK installation
_________________________________
**Work Items**

_SetUp work items [area-Setup]:_
- [x] Visual Studio installer communicates the install folder to the SDK MSI
https://github.com/dotnet/cli/issues/10157
- [x] Manage the SDK bundle installation locations
https://github.com/dotnet/cli/issues/10156
- [x] The SDK bundle installer Procedure [Windows]
https://github.com/dotnet/cli/issues/10155
- [x] SDK resolver in Visual Studio & command shell experience
https://github.com/dotnet/cli/issues/10243
- [x] Add properties to override default location for shared framework installer in Windows
https://github.com/aspnet/AspNetCore/issues/3697
- [x] The Runtime bundle installer Procedure [Windows]
not needed at this time - @rakeshsinghranchi

_Host work items [area-Host]:_
- [x] Runtime dynamic multilevel lookup - muxer
https://github.com/dotnet/core-setup/issues/4637
- [x] SDK muxer [the host] and multi-level lookup
https://github.com/dotnet/cli/issues/10153
- [x] ASP.NET's native code to locate the hostfxr 
https://github.com/aspnet/IISIntegration/issues/1566

_Documentation:_
- [ ] Advertise the dynamic VS/SDK install folder change
https://github.com/dotnet/cli/issues/10152

_Testing:_

SDK bundle 'other-volume' testing...
To install the SDK bundle to another volume:
Example:
`dotnet-sdk-3.0.100-alpha1-009719-win-x64.exe /install DOTNETHOME_X64="D:\dotnet\x64" DOTNETHOME_X86="D:\dotnet\x86" /log "installation.log" /quiet /norestart`
